services:
  mysql:
    image: mysql
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acceso
      MYSQL_USER: alvaro
      MYSQL_PASSWORD: alvaro
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Aquí se agrega el script SQL

volumes:
  mysql_data:
